/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;
import clases.ConectorDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import clases.Usuario;
import clases.AntiInyeccionSQL;
import com.sun.awt.AWTUtilities;
import java.awt.event.KeyEvent;
          

/**
 *
 * @author Fabricio Mero
 */
public class Pantalla_acceso extends javax.swing.JFrame {
    
    /**
     * Creates new form Inicio
     */
    public Pantalla_acceso() {
        initComponents();
        this.setLocationRelativeTo(null); //Centrar pantalla
        AWTUtilities.setWindowOpaque(this, false);
        TextPrompt usua = new TextPrompt("usuario", txb_usuario);
        TextPrompt clav = new TextPrompt("clave", txb_clave);
    }
    
    // Objeto con metodos para eliminar caracteres peligrosos en entrada de usuario.
    AntiInyeccionSQL desinfectante = new AntiInyeccionSQL();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txb_usuario = new javax.swing.JTextField();
        txb_clave = new javax.swing.JPasswordField();
        btn_login_aceptar = new javax.swing.JButton();
        btn_login_cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 275));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txb_usuario.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        getContentPane().add(txb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, 30));

        txb_clave.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        getContentPane().add(txb_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 160, 30));

        btn_login_aceptar.setText("ACEPTAR");
        btn_login_aceptar.setActionCommand("INGRESAR");
        btn_login_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_aceptarActionPerformed(evt);
            }
        });
        btn_login_aceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_login_aceptarKeyPressed(evt);
            }
        });
        getContentPane().add(btn_login_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 100, -1));

        btn_login_cancelar.setText("SALIR");
        btn_login_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INGRESO AL SISTEMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogin.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /* VARIABLES GLOBALES */
    int n_intentos_login = 0;
    /* //VARIABLES GLOBALES */ 

    private void btn_login_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_aceptarActionPerformed
        // Se valida el usuario y clave ingresados.
        validar_usuario();
    }//GEN-LAST:event_btn_login_aceptarActionPerformed

    private void validar_usuario(){
         // Obtenemos credenciales ingresadas por usuario.
        String usuario_ingresado = desinfectante.limpiar_string(txb_usuario.getText());
        String clave_ingresada = desinfectante.limpiar_string(String.valueOf(txb_clave.getPassword()));
        //String usuario_ingresado = txb_usuario.getText();
        //String clave_ingresada = String.valueOf(txb_clave.getPassword());
        
        System.out.println(usuario_ingresado + " " + clave_ingresada);
        
        //ConectorDB conector = new ConectorDB(); ORIGINAL
        
        //ResultSet rs = conector.consultar("SELECT * FROM tbl_usuario");
        
        //ResultSet rs = conector.consultar("SELECT * FROM tbl_usuario where 
        //cl_usuario='" + usuario_ingresado + "' and cl_clave='" + clave_ingresada + "'");  ORIGINAL
        
        // DEBUG
        //System.out.println("SELECT * FROM tbl_usuario where cl_usuario='" + usuario_ingresado + "' and cl_clave='" + clave_ingresada + "'");
        //' or '1'='1      ' or '1'='1'; create table chuta (valor int) --
        // DEBUG
        
        // Si algo falla en la ejecucion de la consulta.
        //if(rs == null)            ORIGINAL
        //{
        //   JOptionPane.showMessageDialog(null, "Ha habido un error."
        //            + "\nPor favor contacte al administrador del sistema.");
        //    System.exit(0);
        //}
        
        
        try {
           // Si se devuelven filas, ha habido una coincidencia de usuario y clave. 
            //if (rs.next()){ // ORIGINAL
            if (true){ // DEBUG
                //if (rs.getString("cl_permiso").equals("A")){ // ORIGINAL
                if (true){ // DEBUG
                    // Es usuario administrador
                    Pantalla_principal acceso= new Pantalla_principal(true);
                    acceso.setVisible(true);
                }
                else{
                    Pantalla_principal acceso= new Pantalla_principal(false);
                    acceso.setVisible(true);
                }
                
                // Ocultamos pantalla de acceso.
                this.setVisible(false);
                return;
            }
                

            /*
            while (rs.next()) {
                
                if(usuario_ingresado.equals(rs.getString("cl_usuario")) &&
                        clave_ingresada.equals(rs.getString("cl_clave")))
                {
                    Pantalla_principal acceso= new Pantalla_principal();
                    acceso.setVisible(true);
                    this.setVisible(false);
                    // Si las credenciales coinciden, la funcion retorna aqui.
                    return;
                }
            }*/
            
            // Si las credenciales no se halla en la DB, aumente un intento de acceso fallido.
            n_intentos_login++;

            // A los 3 intentos fallidos, cierre la aplicacion.
            if(this.n_intentos_login == 4)
            {
                JOptionPane.showMessageDialog(null, "Ha alcanzado el máximo número de intentos permitidos.");
                System.exit(0);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Usuario y/o clave incorrectos");
                this.txb_usuario.setText("");
                this.txb_clave.setText("");
            }
            
        } catch (Exception e ) {
            System.out.println("Error en obtencio de datos DB: " +e);
        }
    }
    
    private void btn_login_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_cancelarActionPerformed
                        System.exit(0); //Salir
    }//GEN-LAST:event_btn_login_cancelarActionPerformed

    private void btn_login_aceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_login_aceptarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            validar_usuario();
        }
    }//GEN-LAST:event_btn_login_aceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login_aceptar;
    private javax.swing.JButton btn_login_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txb_clave;
    private javax.swing.JTextField txb_usuario;
    // End of variables declaration//GEN-END:variables
}
